spring:
  datasource:
    # 配置自带数据库的相对路径
    #url: jdbc:h2:~/.chat2db/db/chat2db_dev;FILE_LOCK=NO;MODE=MYSQL
    url: jdbc:mysql://localhost:3306/chat2db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: tan12345
    driver-class-name: com.mysql.jdbc.Driver
# 端口号
server:
  port: 10821

chat2db:
  gateway:
    base-url: http://test.sqlgpt.cn/gateway
    model-base-url: http://test.sqlgpt.cn/gateway